import { GrievanceStatus, PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';
const prisma = new PrismaClient();
const departments = [
  ['education_dept', 'Education / Scholarship', 'शिक्षा / छात्रवृत्ति', 'शिक्षण / शिष्यवृत्ती', 'EDUCATION'], ['epfo_dept', 'EPFO (Employees Provident Fund)', 'ईपीएफओ (कर्मचारी भविष्य निधि)', 'ईपीएफओ (कर्मचारी भविष्य निधी)', 'LABOUR'], ['railways_dept', 'Railways', 'रेलवे', 'रेल्वे', 'TRANSPORT'], ['municipal_dept', 'Municipal Services', 'नगरपालिका सेवाएं', 'नगरपालिका सेवा', 'MUNICIPAL'], ['food_supply_dept', 'Food, Civil Supplies & Consumer Protection', 'खाद्य, नागरिक आपूर्ति और उपभोक्ता संरक्षण', 'अन्न, नागरी पुरवठा आणि ग्राहक संरक्षण', 'FOOD_SUPPLIES'], ['electricity_dept', 'Electricity / Power Department', 'बिजली / विद्युत विभाग', 'वीज / वीज विभाग', 'ENERGY'], ['water_supply_dept', 'Water Supply & Sanitation', 'जल आपूर्ति और स्वच्छता', 'पाणी पुरवठा आणि स्वच्छता', 'WATER'], ['health_dept', 'Health & Family Welfare', 'स्वास्थ्य और परिवार कल्याण', 'आरोग्य आणि कुटुंब कल्याण', 'HEALTH'], ['roads_dept', 'Roads & Transport', 'सड़क और परिवहन', 'रस्ते आणि वाहतूक', 'ROADS'], ['housing_dept', 'Housing & Urban Development', 'आवास और शहरी विकास', 'निवास और शहरी विकास', 'HOUSING'], ['agriculture_dept', 'Agriculture & Farmers Welfare', 'कृषि और किसान कल्याण', 'कृषी आणि शेतकरी कल्याण', 'AGRICULTURE']
] as const;
async function main() {
  const passwordHash = await bcrypt.hash('demo123', 12);
  for (const [id, nameEn, nameHi, nameMr, category] of departments) await prisma.department.upsert({ where: { id }, update: { nameEn, nameHi, nameMr, category }, create: { id, nameEn, nameHi, nameMr, category } });
  const user = await prisma.user.upsert({ where: { mobile: '9876543210' }, update: { name: 'Rajesh Kumar', email: 'rajesh@example.com', passwordHash, preferredLanguage: 'en' }, create: { name: 'Rajesh Kumar', mobile: '9876543210', email: 'rajesh@example.com', passwordHash, preferredLanguage: 'en' } });
  const submittedAt = new Date(); submittedAt.setDate(submittedAt.getDate() - 25); const dueAt = new Date(submittedAt); dueAt.setDate(dueAt.getDate() + 21);
  await prisma.grievance.upsert({ where: { grievanceNumber: 'GRVDEMO0001' }, update: {}, create: { grievanceNumber: 'GRVDEMO0001', userId: user.id, title: 'Scholarship not received for three months', description: 'I applied for a scholarship but have not received the payment for the last three months.', departmentId: 'education_dept', category: 'Payment Delay', state: 'Maharashtra', district: 'Mumbai', status: GrievanceStatus.UNDER_REVIEW, submittedAt, dueAt, events: { create: { status: 'SUBMITTED', messageEn: 'Grievance submitted successfully', messageHi: 'शिकायत सफलतापूर्वक जमा की गई', messageMr: 'तक्रार यशस्वीरित्या सबमिट केली', createdAt: submittedAt } } } });
}
main().finally(() => prisma.$disconnect());
