-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";
CREATE TYPE "GrievanceStatus" AS ENUM ('SUBMITTED', 'RECEIVED', 'UNDER_REVIEW', 'RESOLVED', 'CLOSED', 'ESCALATED');
CREATE TABLE "User" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "mobile" TEXT NOT NULL, "email" TEXT, "passwordHash" TEXT, "preferredLanguage" TEXT NOT NULL DEFAULT 'en', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Department" ("id" TEXT NOT NULL, "nameEn" TEXT NOT NULL, "nameHi" TEXT NOT NULL, "nameMr" TEXT NOT NULL, "category" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Department_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Grievance" ("id" TEXT NOT NULL, "grievanceNumber" TEXT NOT NULL, "userId" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "departmentId" TEXT NOT NULL, "category" TEXT NOT NULL, "state" TEXT NOT NULL, "district" TEXT NOT NULL, "status" "GrievanceStatus" NOT NULL DEFAULT 'SUBMITTED', "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "dueAt" TIMESTAMP(3) NOT NULL, "resolution" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Grievance_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GrievanceEvent" ("id" TEXT NOT NULL, "grievanceId" TEXT NOT NULL, "status" TEXT NOT NULL, "messageEn" TEXT NOT NULL, "messageHi" TEXT NOT NULL, "messageMr" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "GrievanceEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Attachment" ("id" TEXT NOT NULL, "grievanceId" TEXT NOT NULL, "fileName" TEXT NOT NULL, "fileType" TEXT NOT NULL, "storageKey" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Attachment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Feedback" ("id" TEXT NOT NULL, "grievanceId" TEXT NOT NULL, "rating" INTEGER NOT NULL, "comment" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Feedback_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Appeal" ("id" TEXT NOT NULL, "grievanceId" TEXT NOT NULL, "reason" TEXT NOT NULL, "description" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Appeal_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_mobile_key" ON "User"("mobile"); CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE UNIQUE INDEX "Grievance_grievanceNumber_key" ON "Grievance"("grievanceNumber"); CREATE INDEX "Grievance_userId_idx" ON "Grievance"("userId"); CREATE INDEX "Grievance_status_idx" ON "Grievance"("status"); CREATE INDEX "Grievance_departmentId_idx" ON "Grievance"("departmentId"); CREATE INDEX "GrievanceEvent_grievanceId_createdAt_idx" ON "GrievanceEvent"("grievanceId", "createdAt"); CREATE UNIQUE INDEX "Attachment_storageKey_key" ON "Attachment"("storageKey"); CREATE INDEX "Attachment_grievanceId_idx" ON "Attachment"("grievanceId"); CREATE UNIQUE INDEX "Feedback_grievanceId_key" ON "Feedback"("grievanceId"); CREATE UNIQUE INDEX "Appeal_grievanceId_key" ON "Appeal"("grievanceId"); CREATE INDEX "Appeal_status_idx" ON "Appeal"("status");
ALTER TABLE "Grievance" ADD CONSTRAINT "Grievance_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Grievance" ADD CONSTRAINT "Grievance_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "GrievanceEvent" ADD CONSTRAINT "GrievanceEvent_grievanceId_fkey" FOREIGN KEY ("grievanceId") REFERENCES "Grievance"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Attachment" ADD CONSTRAINT "Attachment_grievanceId_fkey" FOREIGN KEY ("grievanceId") REFERENCES "Grievance"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Feedback" ADD CONSTRAINT "Feedback_grievanceId_fkey" FOREIGN KEY ("grievanceId") REFERENCES "Grievance"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Appeal" ADD CONSTRAINT "Appeal_grievanceId_fkey" FOREIGN KEY ("grievanceId") REFERENCES "Grievance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
